/**
 * Forecast Service:
 * 
 * Mathematical Approach:
 * Least-Squares Linear Regression (y = mx + c)
 * 
 * Mechanics:
 * Given a chronological series of historical data points (x_i, y_i) where:
 *   - x_i is the time step index (0, 1, 2, ... n-1)
 *   - y_i is the value (daily revenue or daily bookings count)
 * 
 * We calculate:
 *   1. Mean of x and Mean of y
 *   2. Slope (m) = sum((x_i - mean_x) * (y_i - mean_y)) / sum((x_i - mean_x)^2)
 *   3. Intercept (c) = mean_y - m * mean_x
 * 
 * Future predictions are generated by projecting the linear model forward:
 *   - y_future = m * x_future + c (where x_future = n, n+1, ..., n+days)
 *   - Values are clamped to 0 to prevent negative revenue/booking forecasts.
 * 
 * Why this was chosen:
 * Linear regression is deterministic, transparent, and computationally light. It requires
 * no complex time-series library dependencies (like ARIMA or Prophet) and its mathematical
 * derivation can be explained easily in interviews.
 */

const Booking = require('../models/Booking');

/**
 * Generate a forecast for bookings or revenue.
 * @param {string} type - 'bookings' or 'revenue'
 * @param {number} forecastDays - number of days to project (30, 60, 90)
 * @returns {Promise<Object>} historical and projected trend series
 */
const generateForecast = async (type = 'revenue', forecastDays = 30) => {
  // 1. Fetch trailing 90 days of historical data (daily grouping)
  const trailingDays = 90;
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - trailingDays);

  const matchQuery = {
    createdAt: { $gte: cutoffDate },
    status: { $ne: 'cancelled' } // ignore cancelled bookings
  };

  if (type === 'revenue') {
    matchQuery.paymentStatus = 'paid';
  }

  // Aggregate daily history
  const historyRaw = await Booking.aggregate([
    { $match: matchQuery },
    {
      $group: {
        _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } },
        value: { $sum: type === 'revenue' ? "$totalPrice" : 1 }
      }
    },
    { $sort: { _id: 1 } }
  ]);

  // Construct complete daily sequence (filling empty days with 0)
  const historyMap = new Map(historyRaw.map(h => [h._id, h.value]));
  const historySeries = [];
  const currentDate = new Date(cutoffDate);
  const today = new Date();

  while (currentDate <= today) {
    const dateStr = currentDate.toISOString().split('T')[0];
    historySeries.push({
      date: dateStr,
      value: historyMap.get(dateStr) || 0,
      isProjected: false
    });
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // 2. Perform Least-Squares Linear Regression
  const n = historySeries.length;
  if (n < 2) {
    // Edge case: not enough data points
    return {
      history: historySeries,
      projection: [],
      slope: 0,
      intercept: 0,
      hasEnoughData: false
    };
  }

  let sumX = 0;
  let sumY = 0;
  let sumXY = 0;
  let sumXX = 0;

  for (let i = 0; i < n; i++) {
    const x = i;
    const y = historySeries[i].value;
    sumX += x;
    sumY += y;
    sumXY += x * y;
    sumXX += x * x;
  }

  const meanX = sumX / n;
  const meanY = sumY / n;

  let num = 0;
  let den = 0;
  for (let i = 0; i < n; i++) {
    const x = i;
    const y = historySeries[i].value;
    num += (x - meanX) * (y - meanY);
    den += (x - meanX) * (x - meanX);
  }

  const slope = den !== 0 ? num / den : 0;
  const intercept = meanY - slope * meanX;

  // 3. Generate future projection
  const projectionSeries = [];
  const projStartDate = new Date(today);

  for (let i = 1; i <= forecastDays; i++) {
    projStartDate.setDate(projStartDate.getDate() + 1);
    const dateStr = projStartDate.toISOString().split('T')[0];
    const xFuture = n - 1 + i;
    const rawVal = slope * xFuture + intercept;
    const val = Math.max(0, Math.round(rawVal * 100) / 100); // Clamp below zero

    projectionSeries.push({
      date: dateStr,
      value: val,
      isProjected: true
    });
  }

  // Count active non-zero points to evaluate data confidence
  const nonZeroPoints = historySeries.filter(h => h.value > 0).length;
  const hasEnoughData = nonZeroPoints >= 5;

  return {
    history: historySeries,
    projection: projectionSeries,
    slope: Math.round(slope * 1000) / 1000,
    intercept: Math.round(intercept * 100) / 100,
    hasEnoughData
  };
};

module.exports = {
  generateForecast
};
